DROP TABLE IF EXISTS quotes;

CREATE TABLE quotes(
id SERIAL PRIMARY KEY,
quote  VARCHAR(1000) NOT NULL,
author VARCHAR(1000) NOT NULL
);

INSERT INTO quotes(quote,author) VALUES ('Life isn’t about getting and having, it’s about giving and being.','Kevin Kruse');
INSERT INTO quotes(quote,author) VALUES ('Whatever the mind of man can conceive and believe, it can achieve.','Napoleon Hill');
INSERT INTO quotes(quote,author) VALUES ('Strive not to be a success, but rather to be of value.','Albert Einstein');
INSERT INTO quotes(quote,author) VALUES ('Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.','Robert Frost');
INSERT INTO quotes(quote,author) VALUES ('I attribute my success to this: I never gave or took any excuse.','Florence Nightingale');
INSERT INTO quotes(quote,author) VALUES ('You miss 100% of the shots you don’t take.','Wayne Gretzky');
INSERT INTO quotes(quote,author) VALUES ('I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.','Michael Jordan');
INSERT INTO quotes(quote,author) VALUES ('The most difficult thing is the decision to act, the rest is merely tenacity.','Amelia Earhart');
INSERT INTO quotes(quote,author) VALUES ('Every strike brings me closer to the next home run.','Babe Ruth');
INSERT INTO quotes(quote,author) VALUES ('Definiteness of purpose is the starting point of all achievement.','W. Clement Stone');
INSERT INTO quotes(quote,author) VALUES ('We must balance conspicuous consumption with conscious capitalism.','Kevin Kruse');
INSERT INTO quotes(quote,author) VALUES ('Life is what happens to you while you’re busy making other plans.','John Lennon');
INSERT INTO quotes(quote,author) VALUES ('We become what we think about.','Earl Nightingale');
INSERT INTO quotes(quote,author) VALUES ('Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.','Mark Twain');
INSERT INTO quotes(quote,author) VALUES ('Life is 10% what happens to me and 90% of how I react to it.','Charles Swindoll');
INSERT INTO quotes(quote,author) VALUES ('The most common way people give up their power is by thinking they don’t have any.','Alice Walker');
INSERT INTO quotes(quote,author) VALUES ('The mind is everything. What you think you become.','Buddha');
INSERT INTO quotes(quote,author) VALUES ('The best time to plant a tree was 20 years ago. The second best time is now.','Chinese Proverb');
INSERT INTO quotes(quote,author) VALUES ('An unexamined life is not worth living.','Socrates');
INSERT INTO quotes(quote,author) VALUES ('Eighty percent of success is showing up.','Woody Allen');
INSERT INTO quotes(quote,author) VALUES ('Your time is limited, so don’t waste it living someone else’s life.','Steve Jobs');
INSERT INTO quotes(quote,author) VALUES ('Winning isn’t everything, but wanting to win is.','Vince Lombardi');
INSERT INTO quotes(quote,author) VALUES ('I am not a product of my circumstances. I am a product of my decisions.','Stephen Covey');
INSERT INTO quotes(quote,author) VALUES ('Every child is an artist.  The problem is how to remain an artist once he grows up.','Pablo Picasso');
INSERT INTO quotes(quote,author) VALUES ('You can never cross the ocean until you have the courage to lose sight of the shore.','Christopher Columbus');
INSERT INTO quotes(quote,author) VALUES ('I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.','Maya Angelou');
INSERT INTO quotes(quote,author) VALUES ('Either you run the day, or the day runs you.','Jim Rohn');
INSERT INTO quotes(quote,author) VALUES ('Whether you think you can or you think you can’t, you’re right.','Henry Ford');
INSERT INTO quotes(quote,author) VALUES ('The two most important days in your life are the day you are born and the day you find out why.','Mark Twain');
INSERT INTO quotes(quote,author) VALUES ('Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.','Johann Wolfgang von Goethe');
INSERT INTO quotes(quote,author) VALUES ('The best revenge is massive success.','Frank Sinatra');
INSERT INTO quotes(quote,author) VALUES ('People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.','Zig Ziglar');
INSERT INTO quotes(quote,author) VALUES ('Life shrinks or expands in proportion to one’s courage.','Anais Nin');
INSERT INTO quotes(quote,author) VALUES ('If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.','Vincent Van Gogh');
INSERT INTO quotes(quote,author) VALUES ('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.','Aristotle');
INSERT INTO quotes(quote,author) VALUES ('Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.','Jesus');
INSERT INTO quotes(quote,author) VALUES ('The only person you are destined to become is the person you decide to be.','Ralph Waldo Emerson');
INSERT INTO quotes(quote,author) VALUES ('Go confidently in the direction of your dreams.  Live the life you have imagined.','Henry David Thoreau');
INSERT INTO quotes(quote,author) VALUES ('When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.','Erma Bombeck');
INSERT INTO quotes(quote,author) VALUES ('Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.','Booker T. Washington');
INSERT INTO quotes(quote,author) VALUES ('Certain things catch your eye, but pursue only those that capture the heart.','Ancient Indian Proverb');
INSERT INTO quotes(quote,author) VALUES ('Believe you can and you’re halfway there.','Theodore Roosevelt');
INSERT INTO quotes(quote,author) VALUES ('Everything you’ve ever wanted is on the other side of fear.','George Addair');
INSERT INTO quotes(quote,author) VALUES ('We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.','Plato');
INSERT INTO quotes(quote,author) VALUES ('Teach thy tongue to say, “I do not know,” and thous shalt progress.','Maimonides');
INSERT INTO quotes(quote,author) VALUES ('Start where you are. Use what you have.  Do what you can.','Arthur Ashe');
INSERT INTO quotes(quote,author) VALUES ('When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life.','John Lennon');
INSERT INTO quotes(quote,author) VALUES ('Fall seven times and stand up eight.','Japanese Proverb');
INSERT INTO quotes(quote,author) VALUES ('When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.','Helen Keller');
INSERT INTO quotes(quote,author) VALUES ('Everything has beauty, but not everyone can see.','Confucius');
INSERT INTO quotes(quote,author) VALUES ('How wonderful it is that nobody need wait a single moment before starting to improve the world.','Anne Frank');
INSERT INTO quotes(quote,author) VALUES ('When I let go of what I am, I become what I might be.','Lao Tzu');
INSERT INTO quotes(quote,author) VALUES ('Life is not measured by the number of breaths we take, but by the moments that take our breath away.','Maya Angelou');
INSERT INTO quotes(quote,author) VALUES ('Happiness is not something readymade.  It comes from your own actions.','Dalai Lama');
INSERT INTO quotes(quote,author) VALUES ('If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.','Sheryl Sandberg');
INSERT INTO quotes(quote,author) VALUES ('First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.','Aristotle');
INSERT INTO quotes(quote,author) VALUES ('If the wind will not serve, take to the oars.','Latin Proverb');
INSERT INTO quotes(quote,author) VALUES ('You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.','Unknown');
INSERT INTO quotes(quote,author) VALUES ('We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.','Marie Curie');
INSERT INTO quotes(quote,author) VALUES ('Too many of us are not living our dreams because we are living our fears.','Les Brown');
INSERT INTO quotes(quote,author) VALUES ('Challenges are what make life interesting and overcoming them is what makes life meaningful.','Joshua J. Marine');
INSERT INTO quotes(quote,author) VALUES ('If you want to lift yourself up, lift up someone else.','Booker T. Washington');
INSERT INTO quotes(quote,author) VALUES ('I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.','Leonardo da Vinci');
INSERT INTO quotes(quote,author) VALUES ('Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.','Jamie Paolinetti');
INSERT INTO quotes(quote,author) VALUES ('You take your life in your own hands, and what happens? A terrible thing, no one to blame.','Erica Jong');
INSERT INTO quotes(quote,author) VALUES ('What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.','Bob Dylan');
INSERT INTO quotes(quote,author) VALUES ('I didn’t fail the test. I just found 100 ways to do it wrong.','Benjamin Franklin');
INSERT INTO quotes(quote,author) VALUES ('In order to succeed, your desire for success should be greater than your fear of failure.','Bill Cosby');
INSERT INTO quotes(quote,author) VALUES ('A person who never made a mistake never tried anything new.','Albert Einstein');
INSERT INTO quotes(quote,author) VALUES ('The person who says it cannot be done should not interrupt the person who is doing it.','Chinese Proverb');
INSERT INTO quotes(quote,author) VALUES ('There are no traffic jams along the extra mile.','Roger Staubach');
INSERT INTO quotes(quote,author) VALUES ('It is never too late to be what you might have been.','George Eliot');
INSERT INTO quotes(quote,author) VALUES ('You become what you believe.','Oprah Winfrey');
INSERT INTO quotes(quote,author) VALUES ('I would rather die of passion than of boredom.','Vincent van Gogh');
INSERT INTO quotes(quote,author) VALUES ('A truly rich man is one whose children run into his arms when his hands are empty.','Unknown');
INSERT INTO quotes(quote,author) VALUES ('It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.','Ann Landers');
INSERT INTO quotes(quote,author) VALUES ('If you want your children to turn out well, spend twice as much time with them, and half as much money.','Abigail Van Buren');
INSERT INTO quotes(quote,author) VALUES ('Build your own dreams, or someone else will hire you to build theirs.','Farrah Gray');
INSERT INTO quotes(quote,author) VALUES ('The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.','Jesse Owens');
INSERT INTO quotes(quote,author) VALUES ('Education costs money.  But then so does ignorance.','Sir Claus Moser');
INSERT INTO quotes(quote,author) VALUES ('I have learned over the years that when one’s mind is made up, this diminishes fear.','Rosa Parks');
INSERT INTO quotes(quote,author) VALUES ('It does not matter how slowly you go as long as you do not stop.','Confucius');
INSERT INTO quotes(quote,author) VALUES ('If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.','Oprah Winfrey');
INSERT INTO quotes(quote,author) VALUES ('Remember that not getting what you want is sometimes a wonderful stroke of luck.','Dalai Lama');
INSERT INTO quotes(quote,author) VALUES ('You can’t use up creativity.  The more you use, the more you have.','Maya Angelou');
INSERT INTO quotes(quote,author) VALUES ('Dream big and dare to fail.','Norman Vaughan');
INSERT INTO quotes(quote,author) VALUES ('Our lives begin to end the day we become silent about things that matter.','Martin Luther King Jr.');
INSERT INTO quotes(quote,author) VALUES ('Do what you can, where you are, with what you have.','Teddy Roosevelt');
INSERT INTO quotes(quote,author) VALUES ('If you do what you’ve always done, you’ll get what you’ve always gotten.','Tony Robbins');
INSERT INTO quotes(quote,author) VALUES ('Dreaming, after all, is a form of planning.','Gloria Steinem');
INSERT INTO quotes(quote,author) VALUES ('It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live.','Mae Jemison');
INSERT INTO quotes(quote,author) VALUES ('You may be disappointed if you fail, but you are doomed if you don’t try.','Beverly Sills');
INSERT INTO quotes(quote,author) VALUES ('Remember no one can make you feel inferior without your consent.','Eleanor Roosevelt');
INSERT INTO quotes(quote,author) VALUES ('Life is what we make it, always has been, always will be.','Grandma Moses');
INSERT INTO quotes(quote,author) VALUES ('The question isn’t who is going to let me; it’s who is going to stop me.','Ayn Rand');
INSERT INTO quotes(quote,author) VALUES ('When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.','Henry Ford');
INSERT INTO quotes(quote,author) VALUES ('It’s not the years in your life that count. It’s the life in your years.','Abraham Lincoln');
INSERT INTO quotes(quote,author) VALUES ('Change your thoughts and you change your world.','Norman Vincent Peale');
INSERT INTO quotes(quote,author) VALUES ('Either write something worth reading or do something worth writing.','Benjamin Franklin');
INSERT INTO quotes(quote,author) VALUES ('Nothing is impossible, the word itself says, “I’m possible!”','Audrey Hepburn');
INSERT INTO quotes(quote,author) VALUES ('The only way to do great work is to love what you do.','Steve Jobs');
INSERT INTO quotes(quote,author) VALUES ('If you can dream it, you can achieve it.','Zig Ziglar');
